"""Updated schema

Revision ID: b4e7b537d1c0
Revises: c20a985891e5
Create Date: 2026-06-29 00:01:23.643772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e7b537d1c0'
down_revision: Union[str, Sequence[str], None] = 'c20a985891e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['articlemetadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('article_type', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('articlemetadata', sa.Column('snippet', sa.String(length=1000), nullable=True))
    op.add_column('articlemetadata', sa.Column('is_populated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articlemetadata', 'is_populated')
    op.drop_column('articlemetadata', 'snippet')
    op.alter_column('article_type', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('article_details')
    # ### end Alembic commands ###
