import json

from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    AIMessage
)
from langchain_core.prompts import PromptTemplate

from schemas.state import AgentState

from utilities.load_model import load_models
from utilities.dependency_helper import get_task


QUERY_SYSTEM_PROMPT = PromptTemplate.from_template("""
You are a task-support assistant.

Your job is to answer a query generated by the
Context Synthesizer.

Provide only the information requested.

Be concise and factual.

Return plain text.

Here is the context. Answer based on the context ONLY.
## Context
{context}
""")


async def answer_query_node(state: AgentState):

    task = get_task(
        state,
        state["current_task_id"]
    )

    assert task is not None

    artifacts_key = f"{task['id']}_{task['type']}"

    query_history = state["artifacts"].get(
        artifacts_key
    )

    if not query_history:
        return {}

    latest = query_history[-1]

    llm = load_models("Planner")
    response = await llm.ainvoke(
        [
            SystemMessage(
                content=QUERY_SYSTEM_PROMPT.format(context=json.dumps(query_history, indent=2))
            ),
            HumanMessage(
                content=latest['query']
            )
        ]
    )

    latest["query_response"] = {
        "answer": response.content
    }

    query_history[-1] = latest

    state["artifacts"][artifacts_key] = query_history

    return {
        "artifacts": state["artifacts"],
        "messages": [
            AIMessage(
                content="Query resolved.",
                additional_kwargs={
                    "node_name": "query_node",
                    "next_node": "context_synthesizer"
                }
            )
        ]
    }