import asyncio
import json
import logging

from langchain_core.messages import (
    SystemMessage,
    HumanMessage,
    AIMessage
)
from langchain_core.prompts import PromptTemplate

from schemas.state import AgentState

from utilities.load_model import load_models
from utilities.dependency_helper import get_task

logger = logging.getLogger(__name__)


QUERY_SYSTEM_PROMPT = PromptTemplate.from_template("""
You are a task-support assistant.

Your job is to answer a query generated by the
Context Synthesizer.

Provide only the information requested.

Be concise and factual.

Return plain text.

Here is the context. Answer based on the context ONLY.
## Context
{context}
""")


async def answer_query_node(state: AgentState):
    logger.info("Starting answer_query_node for current_task_id=%s", state.get("current_task_id"))

    task = get_task(
        state,
        state["current_task_id"]
    )

    assert task is not None

    artifacts_key = f"{task['id']}_{task['type']}"

    query_history = state["artifacts"].get(
        artifacts_key
    )

    if not query_history:
        logger.info("No query history found for artifact %s; skipping LLM call", artifacts_key)
        return {}

    latest = query_history[-1]
    logger.info("Preparing query resolution LLM call for artifact %s with latest query=%s", artifacts_key, latest.get("query"))

    llm = load_models("Planner")
    logger.info("Waiting 5 seconds before query resolver LLM call")
    await asyncio.sleep(5)
    logger.info("Making query resolver LLM call")
    response = await llm.ainvoke(
        [
            SystemMessage(
                content=QUERY_SYSTEM_PROMPT.format(context=json.dumps(query_history, indent=2))
            ),
            HumanMessage(
                content=latest['query']
            )
        ]
    )

    logger.info("Received query resolution response for artifact %s", artifacts_key)
    latest["query_response"] = {
        "answer": response.content
    }

    query_history[-1] = latest

    state["artifacts"][artifacts_key] = query_history

    logger.info("Completed answer_query_node for artifact %s", artifacts_key)
    return {
        "artifacts": state["artifacts"],
        "messages": [
            AIMessage(
                content="Query resolved.",
                additional_kwargs={
                    "node_name": "query_node",
                    "next_node": "context_synthesizer"
                }
            )
        ]
    }